// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VH.Data.EFCore
{
    public partial class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
    }
}