// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VH.Data.EFCore
{
    public partial class Order
    {
        public Order()
        {
            Payment = new HashSet<Payment>();
        }

        public int Id { get; set; }
        public string Status { get; set; }
        public DateTimeOffset From { get; set; }
        public DateTimeOffset To { get; set; }
        public int CustomerId { get; set; }
        public int LocationId { get; set; }
        public int RentableItemId { get; set; }
        public string StatusBefore { get; set; }
        public string StatusAfter { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Location Location { get; set; }
        public virtual RentableItem RentableItem { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}