// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VH.Data.EFCore
{
    public partial class Payment
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public decimal Total { get; set; }
        public string TotalCurrency { get; set; }
        public string PaidCurrency { get; set; }
        public decimal? PaidAmmount { get; set; }

        public virtual Order Order { get; set; }
    }
}